# Generated by Django 5.2.4 on 2025-07-26 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreasConocimiento',
            fields=[
                ('id_area_conocimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_area', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Área de Conocimiento',
                'verbose_name_plural': 'Áreas de Conocimiento',
                'db_table': 'areas_conocimiento',
            },
        ),
        migrations.CreateModel(
            name='Bancos',
            fields=[
                ('id_banco', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_banco', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'db_table': 'bancos',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(help_text='Dato de login para todos los usuarios.', max_length=100, unique=True)),
                ('password', models.CharField(help_text='Debe almacenarse de forma encriptada (hash).', max_length=255)),
                ('tipo_usuario', models.CharField(choices=[('HiringGroup', 'Hiring Group'), ('Empresa', 'Empresa'), ('Postulante', 'Postulante')], help_text='Discriminador para identificar el tipo de usuario.', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Nominas',
            fields=[
                ('id_nomina', models.AutoField(primary_key=True, serialize=False)),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.CharField(choices=[('Generada', 'Generada'), ('Pagada', 'Pagada')], default='Generada', max_length=10)),
            ],
            options={
                'verbose_name': 'Nómina',
                'verbose_name_plural': 'Nóminas',
                'db_table': 'nominas',
            },
        ),
        migrations.CreateModel(
            name='Postulaciones',
            fields=[
                ('id_postulacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.CharField(choices=[('Recibida', 'Recibida'), ('En Revision', 'En Revisión'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada')], default='Recibida', max_length=12)),
            ],
            options={
                'verbose_name': 'Postulación',
                'verbose_name_plural': 'Postulaciones',
                'db_table': 'postulaciones',
            },
        ),
        migrations.CreateModel(
            name='Universidades',
            fields=[
                ('id_universidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_universidad', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Universidad',
                'verbose_name_plural': 'Universidades',
                'db_table': 'universidades',
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id_empresa', models.OneToOneField(db_column='ID_Empresa', help_text='Clave primaria y foránea que referencia a Usuarios (relación 1-a-1).', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hiring.usuarios')),
                ('nombre_empresa', models.CharField(max_length=150)),
                ('rif', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('sector_industrial', models.CharField(blank=True, max_length=100, null=True)),
                ('persona_contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('email_contacto', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_contratacion', models.DateField()),
                ('tipo_contrato', models.CharField(choices=[('Un mes', 'Un mes'), ('Seis meses', 'Seis meses'), ('Un año', 'Un año'), ('Indefinido', 'Indefinido')], max_length=15)),
                ('salario_acordado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_sangre', models.CharField(blank=True, max_length=5, null=True)),
                ('contacto_emergencia_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto_emergencia_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_cuenta', models.CharField(blank=True, max_length=30, null=True)),
                ('estatus', models.CharField(choices=[('Activo', 'Activo'), ('Finalizado', 'Finalizado')], default='Activo', max_length=10)),
                ('id_banco', models.ForeignKey(blank=True, db_column='ID_Banco', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hiring.bancos')),
                ('id_postulacion', models.OneToOneField(db_column='ID_Postulacion', help_text='Un contrato se origina de una única postulación aceptada.', on_delete=django.db.models.deletion.DO_NOTHING, to='hiring.postulaciones')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': 'contratos',
            },
        ),
        migrations.CreateModel(
            name='Profesiones',
            fields=[
                ('id_profesion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_profesion', models.CharField(max_length=100)),
                ('id_area_conocimiento', models.ForeignKey(blank=True, db_column='ID_Area_Conocimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hiring.areasconocimiento')),
            ],
            options={
                'verbose_name': 'Profesión',
                'verbose_name_plural': 'Profesiones',
                'db_table': 'profesiones',
            },
        ),
        migrations.CreateModel(
            name='Recibos',
            fields=[
                ('id_recibo', models.AutoField(primary_key=True, serialize=False)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_deduccion_inces', models.DecimalField(decimal_places=2, help_text='Calculado como el 0.5% del salario.', max_digits=10)),
                ('monto_deduccion_ivss', models.DecimalField(decimal_places=2, help_text='Calculado como el 1% del salario.', max_digits=10)),
                ('comision_hiring_group', models.DecimalField(decimal_places=2, help_text='Calculado como el 2% del salario.', max_digits=10)),
                ('salario_neto_pagado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('id_contrato', models.ForeignKey(db_column='ID_Contrato', on_delete=django.db.models.deletion.DO_NOTHING, to='hiring.contratos')),
                ('id_nomina', models.ForeignKey(db_column='ID_Nomina', on_delete=django.db.models.deletion.CASCADE, to='hiring.nominas')),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
                'db_table': 'recibos',
            },
        ),
        migrations.CreateModel(
            name='Vacantes',
            fields=[
                ('id_vacante', models.AutoField(primary_key=True, serialize=False)),
                ('cargo_vacante', models.CharField(max_length=150)),
                ('descripcion_perfil', models.TextField()),
                ('salario_ofrecido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva'), ('Cerrada', 'Cerrada')], default='Activa', max_length=10)),
                ('id_profesion', models.ForeignKey(blank=True, db_column='ID_Profesion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hiring.profesiones')),
                ('id_empresa', models.ForeignKey(db_column='ID_Empresa', on_delete=django.db.models.deletion.CASCADE, to='hiring.empresas')),
            ],
            options={
                'verbose_name': 'Vacante',
                'verbose_name_plural': 'Vacantes',
                'db_table': 'vacantes',
            },
        ),
        migrations.AddField(
            model_name='postulaciones',
            name='id_vacante',
            field=models.ForeignKey(db_column='ID_Vacante', on_delete=django.db.models.deletion.CASCADE, to='hiring.vacantes'),
        ),
        migrations.AddField(
            model_name='nominas',
            name='id_empresa',
            field=models.ForeignKey(db_column='ID_Empresa', on_delete=django.db.models.deletion.CASCADE, to='hiring.empresas'),
        ),
        migrations.CreateModel(
            name='Postulantes',
            fields=[
                ('id_postulante', models.OneToOneField(db_column='ID_Postulante', help_text='Clave primaria y foránea que referencia a Usuarios (relación 1-a-1).', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hiring.usuarios')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula_identidad', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('id_universidad', models.ForeignKey(blank=True, db_column='ID_Universidad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hiring.universidades')),
            ],
            options={
                'verbose_name': 'Postulante',
                'verbose_name_plural': 'Postulantes',
                'db_table': 'postulantes',
            },
        ),
        migrations.AddField(
            model_name='postulaciones',
            name='id_postulante',
            field=models.ForeignKey(db_column='ID_Postulante', on_delete=django.db.models.deletion.CASCADE, to='hiring.postulantes'),
        ),
        migrations.CreateModel(
            name='ExperienciasLaborales',
            fields=[
                ('id_experiencia', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=150)),
                ('cargo_ocupado', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, help_text='Nulo si es el trabajo actual.', null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('id_postulante', models.ForeignKey(db_column='ID_Postulante', on_delete=django.db.models.deletion.CASCADE, to='hiring.postulantes')),
            ],
            options={
                'verbose_name': 'Experiencia Laboral',
                'verbose_name_plural': 'Experiencias Laborales',
                'db_table': 'experiencias_laborales',
            },
        ),
        migrations.AlterUniqueTogether(
            name='nominas',
            unique_together={('id_empresa', 'mes', 'anio')},
        ),
        migrations.AlterUniqueTogether(
            name='postulaciones',
            unique_together={('id_postulante', 'id_vacante')},
        ),
    ]
