# Generated by Django 5.2.4 on 2025-07-27 00:53

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='usuarios',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='fecha_creacion',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='password',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table=None,
        ),
    ]
